my_app/accounts/urls.py
import django.contrib.auth.urls
from django.conf.urls import url
from django.urls import include, path

from accounts.views import ActivateUserView, MyProfileView, SignUpView

app_name = 'accounts'

urlpatterns = [
    path('my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('activate/<uuid:username>/', ActivateUserView.as_view(), name='activate-user'),

    url('^', include('django.contrib.auth.urls')),
]

my_app/currency/urls.py
from django.urls import path

from currency.views import *

app_name = 'currency'

urlpatterns = [
    path('contactus/', get_contact_us),

    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', CreateRateViev.as_view(), name='create-rate'),
    path('rate/details/<int:pk>/', DetailRateView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', UpdateRateView.as_view(), name='update-rate'),
    path('rate/delete/<int:pk>/', DeleteRateView.as_view(), name='delete-rate'),
    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', CreateSourceViev.as_view(), name='create-source'),
    path('source/details/<int:pk>/', DetailSourceView.as_view(), name='source-details'),
    path('source/update/<int:pk>/', UpdateSourceView.as_view(), name='update-source'),
    path('source/delete/<int:pk>/', DeleteSorceView.as_view(), name='delete-source'),
    path('contactus/create/', ContactUsCreateViev.as_view(), name='contactus-create'),
    path('rate/latest/', LatestRatesView.as_view(), name='rates-last'),
]

my_app/settings/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('index/', TemplateView.as_view(template_name='index.html'), name='index'),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.v1.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    # API docs
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += [url(r'^silk/', include('silk.urls', namespace=' '))]
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

my_app/currency/models.py
from django.db import models
from django.utils import timezone

from currency import model_choices


# Create your models here.
class ContactUs(models.Model):
    email_to = models.EmailField()
    subject = models.CharField(max_length=255, null=True)
    body = models.CharField(max_length=2056, null=True)
    created = models.DateTimeField(auto_now=True)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=24, unique=True, editable=False)


class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(default=timezone.now())
    source = models.ForeignKey(Source, related_name='rates', on_delete=models.CASCADE)
    curr_type = models.CharField(max_length=3, choices=model_choices.RATE_TYPES,
                                 blank=False, null=False, default=model_choices.TYPE_USD)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=225)
    response_time = models.PositiveSmallIntegerField(default=0)
    request_method = models.CharField(max_length=10, choices=model_choices.REQUEST_METHODS)

my_app/currency/forms.py
from django import forms

from currency import models


class RateForm(forms.ModelForm):
    class Meta:
        model = models.Rate
        fields = ('sale', 'buy', 'source', 'curr_type')


class SourceForm(forms.ModelForm):
    class Meta:
        model = models.Source
        fields = (
            'name',
            'source_url',
        )

my_app/currency/views.py
from urllib.parse import urlencode

from django.conf import settings
from django.core.cache import cache
from django.core.mail import send_mail
from django.forms.models import model_to_dict
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from django_filters.views import FilterView

from currency import model_choices as mch
from currency.filters import RateFilter
from currency.forms import RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.services import get_latest_rates
from currency.tasks import contact_us


class IndexTemplateView(TemplateView):
    template_name = 'index.html'


def get_contact_us(request):
    contacts = ContactUs.objects.all()

    context = {
        "contact_list": contacts
    }

    return render(request, "contact.html", context=context)


class RateListView(FilterView):
    queryset = Rate.objects.all().defer('created').select_related('source').order_by('-created')
    template_name = 'rate_list.html'
    paginate_by = 5
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        get_parameters = {}
        for key, value in self.request.GET.items():
            if key != 'page':
                get_parameters[key] = value

        context['pagination_params'] = urlencode(get_parameters)

        return context


class CreateRateViev(CreateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'create_rate.html'


class DeleteRateView(DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'delete_rate.html'


class UpdateRateView(UpdateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'update_rate.html'


class DetailRateView(DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class SourceListView(ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class CreateSourceViev(CreateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'create_source.html'


class DeleteSorceView(DeleteView):
    queryset = Source.objects.all()
    success_url = reverse_lazy('currency:source-list')
    template_name = 'delete_source.html'


class UpdateSourceView(UpdateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'update_source.html'


class DetailSourceView(DetailView):
    queryset = Source.objects.all()
    template_name = 'sourсe_details.html'


class ContactUsCreateViev(CreateView):
    model = ContactUs
    success_url = reverse_lazy('index')
    template_name = 'create_contactus.html'
    fields = ('email_to', 'subject', 'body')

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        body = form.cleaned_data['body']
        email_to = form.cleaned_data['email_to']

        full_email_body = f'''
        Email To: {email_to}
        Body: {body}
        '''

        contact_us.apply_async(args=(subject,), kwargs={'body': full_email_body})
        return super().form_valid(form)


class LatestRatesView(TemplateView):
    template_name = 'latest_rates_list.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['rate_list'] = get_latest_rates()
        return context

my_app/currency/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Title</title>

        <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    </head>

    <body>

        {% include 'includes/messages.html' %}

        {% include 'includes/navbar.html' %}

        <div class="container">
            {% block main_content %}
            {% endblock %}
        </div>

        {%include 'includes/footer.html'%}

        <script src="{% static 'scripts/jquery-3.5.1.slim.min.js' %}"></script>
        <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    </body>

</html>

my_app/currency/templates/contact.html
{% extends "base.html" %}

{% block main_content%}
<table>
    <colgroup>
        <col style="width: 300px;">
        <col style="width: 500px;">
        <col style="width: 500px;">
    </colgroup>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Message</th>
    </tr>
    {% for contact in contact_list %}
    <tr>
        <td>{{contact.name}}</td>
        <td>{{contact.email}}</td>
        <td>{{contact.text}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock%}

my_app/currency/templates/create_contactus.html
{% extends 'base.html' %}

{% block main_content%}
<br>
<br>
Contact Us
<br>
<br>
<br>

<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <br>
    <br>
    <button type="submit"> Send to server </button>
</form>


{% endblock %}

my_app/currency/templates/create_rate.html
{% extends 'base.html' %}

{% block main_content%}
<br>
<br>
Create new rate
<br>
<br>
<br>

<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <br>
    <br>
    <button type="submit"> Send to server </button>
</form>


{% endblock %}

my_app/currency/templates/create_source.html
{% extends 'base.html' %}

{% block main_content%}
<br>
<br>
Create new Source
<br>
<br>
<br>

<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <br>
    <br>
    <button type="submit"> Send to server </button>
</form>


{% endblock %}

my_app/currency/templates/delete_rate.html
{% extends 'base.html' %}

{% block main_content %}
<br>
<br>
Are you sure you want to delete rate with id: {{ object.id }}?
<br>
<br>
<br>

<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>

{% endblock %}

my_app/currency/templates/index.html
{% extends 'base.html' %}

{% block main_content%}
<div class="row">
    <div class="col">{% lorem %}</div>
    <div class="col">{% lorem %}</div>
    <div class="col">{% lorem %}</div>
</div>
{% endblock %}

my_app/currency/templates/latest_rates_list.html
{% extends 'base.html' %}

{% block main_content %}

<a href="{% url 'currency:create-rate' %}">Create Rate</a>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Sale</th>
        <th>Buy</th>
        <th>Type</th>
        <th>Source</th>
        <th>Actions</th>
    </tr>

    {% for rate in rate_list %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.sale }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.get_curr_type_display }}</td>
        <td><a href="{% url 'currency:source-details' rate.source_id %}">{{ rate.source.name }}</a></td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.pk %}">Details</a>
                    <a class="dropdown-item" href="{% url 'currency:update-rate' rate.pk %}">Update</a>
                    <a class="dropdown-item" href="{% url 'currency:delete-rate' rate.pk %}">Delete</a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

my_app/currency/templates/rate_details.html
{% extends 'base.html' %}

{% block main_content %}

Rate Details

Id: {{ object.id }}<br>
Buy: {{ object.buy }}<br>
Sale: {{ object.sale }}<br>
Create: {{ object.created }}<br>
Source: {{ object.source }}<br>
Type: {{ object.type }}<br>

{% endblock %}

my_app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block main_content %}

<a class="btn btn-primary" href="{% url 'currency:create-rate' %}">Create Rate</a>
<form class="" method="get">
    {{ filter.form.as_p }}
    <button type="submit">Submit</button>
</form>
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Sale</th>
        <th>Buy</th>
        <th>Type</th>
        <th>Source</th>
        <th>Created</th>
        <th>Actions</th>
    </tr>

    {% for rate in rate_list %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.sale }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.created }}</td>
        <td>{{ rate.get_curr_type_display }}</td>
        <td><a href="{% url 'currency:source-details' rate.source_id %}">{{ rate.source.name }}</a></td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.pk %}">Details</a>
                    <a class="dropdown-item" href="{% url 'currency:update-rate' rate.pk %}">Update</a>
                    <a class="dropdown-item" href="{% url 'currency:delete-rate' rate.pk %}">Delete</a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
{% include 'includes/paginator.html' %}
{% endblock %}

my_app/currency/templates/source_list.html
{% extends 'base.html' %}

{% block main_content %}

{% for object in object_list %}
Id: {{ object.id }}<br>
Name: {{ object.name }}<br>

Related Rates
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Sale</th>
        <th>Buy</th>

        <th>Type</th>
        <th>Actions</th>
    </tr>

    {% for rate in object.rates.all %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.sale }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.get_curr_type_display }}</td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.pk %}">Details</a>
                    <a class="dropdown-item" href="{% url 'currency:update-rate' rate.pk %}">Update</a>
                    <a class="dropdown-item" href="{% url 'currency:delete-rate' rate.pk %}">Delete</a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endfor %}
{% endblock %}

my_app/currency/templates/sourсe_details.html
{% extends 'base.html' %}

{% block main_content %}
<br>
<br>
Source Details
<br>
<br>
<br>


Id: {{ object.id }}<br>
Name: {{ object.name }}<br>
Url: {{ object.source_url }}<br>
<!-- 
{{ object.rate_set.all }} -->

{% for rate in object.rates.all %}

ID: {{ rate.id }} Sale: {{ rate.sale }} Buy: {{ rate.buy }} Type: {{ rate.get_curr_type_display }},
<a href="{% url 'currency:source-details' rate.source_id %}">{{ rate.source.name }}</a>
<a href="{% url 'currency:rate-details' rate.pk %}">Details</a>
<a href="{% url 'currency:update-rate' rate.pk %}">Update</a>
<a href="{% url 'currency:delete-rate' rate.pk %}">Delete</a>
</br>

{% endfor %}
{% endblock %}

my_app/currency/templates/update_rate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main_content %}
<br>
<br>
Update Rate
<br>
<br>
<form method="POST">
    {%csrf_token%}
    {{ form|crispy }}
    <br>
    <br>
    <button type="submit">Send To Server</button>
</form>
{% endblock %}

my_app/currency/templates/update_source.html
{% extends 'base.html' %}

{% block main_content %}
<br>
<br>
Update Source
<br>
<br>
<br>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <br>
    <button type="submit">Send To Server</button>
</form>

{% endblock %}