my_app/accounts/urls.py
import django.contrib.auth.urls
from django.conf.urls import url
from django.urls import include, path

from accounts.views import ActivateUserView, MyProfileView, SignUpView

app_name = 'accounts'

urlpatterns = [
    path('my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('activate/<uuid:username>/', ActivateUserView.as_view(), name='activate-user'),

    url('^', include('django.contrib.auth.urls')),
]

my_app/currency/urls.py
from django.urls import path

from currency.views import *

app_name = 'currency'

urlpatterns = [
    path('contactus/', get_contact_us),

    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', CreateRateViev.as_view(), name='create-rate'),
    path('rate/details/<int:pk>/', DetailRateView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', UpdateRateView.as_view(), name='update-rate'),
    path('rate/delete/<int:pk>/', DeleteRateView.as_view(), name='delete-rate'),
    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', CreateSourceViev.as_view(), name='create-source'),
    path('source/details/<int:pk>/', DetailSourceView.as_view(), name='source-details'),
    path('source/update/<int:pk>/', UpdateSourceView.as_view(), name='update-source'),
    path('source/delete/<int:pk>/', DeleteSorceView.as_view(), name='delete-source'),
    path('contactus/create/', ContactUsCreateViev.as_view(), name='contactus-create'),
    path('rate/latest/', LatestRatesView.as_view(), name='rates-last'),
]

my_app/settings/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('index/', TemplateView.as_view(template_name='index.html'), name='index'),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.v1.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    # API docs
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += [url(r'^silk/', include('silk.urls', namespace=' '))]
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

my_app/currency/models.py
from django.db import models
from django.utils import timezone

from currency import model_choices


# Create your models here.
class ContactUs(models.Model):
    email_to = models.EmailField()
    subject = models.CharField(max_length=255, null=True)
    body = models.CharField(max_length=2056, null=True)
    created = models.DateTimeField(auto_now=True)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=24, unique=True, editable=False)


class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(default=timezone.now())
    source = models.ForeignKey(Source, related_name='rates', on_delete=models.CASCADE)
    curr_type = models.CharField(max_length=3, choices=model_choices.RATE_TYPES,
                                 blank=False, null=False, default=model_choices.TYPE_USD)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=225)
    response_time = models.PositiveSmallIntegerField(default=0)
    request_method = models.CharField(max_length=10, choices=model_choices.REQUEST_METHODS)

my_app/currency/forms.py
from django import forms

from currency import models


class RateForm(forms.ModelForm):
    class Meta:
        model = models.Rate
        fields = ('sale', 'buy', 'source', 'curr_type')


class SourceForm(forms.ModelForm):
    class Meta:
        model = models.Source
        fields = (
            'name',
            'source_url',
        )

my_app/currency/views.py
from urllib.parse import urlencode

from django.conf import settings
from django.core.cache import cache
from django.core.mail import send_mail
from django.forms.models import model_to_dict
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from django_filters.views import FilterView

from currency import model_choices as mch
from currency.filters import RateFilter
from currency.forms import RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.services import get_latest_rates
from currency.tasks import contact_us


class IndexTemplateView(TemplateView):
    template_name = 'index.html'


def get_contact_us(request):
    contacts = ContactUs.objects.all()

    context = {
        "contact_list": contacts
    }

    return render(request, "contact.html", context=context)


class RateListView(FilterView):
    queryset = Rate.objects.all().defer('created').select_related('source').order_by('-created')
    template_name = 'rate_list.html'
    paginate_by = 5
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        get_parameters = {}
        for key, value in self.request.GET.items():
            if key != 'page':
                get_parameters[key] = value

        context['pagination_params'] = urlencode(get_parameters)

        return context


class CreateRateViev(CreateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'create_rate.html'


class DeleteRateView(DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'delete_rate.html'


class UpdateRateView(UpdateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'update_rate.html'


class DetailRateView(DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class SourceListView(ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class CreateSourceViev(CreateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'create_source.html'


class DeleteSorceView(DeleteView):
    queryset = Source.objects.all()
    success_url = reverse_lazy('currency:source-list')
    template_name = 'delete_source.html'


class UpdateSourceView(UpdateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'update_source.html'


class DetailSourceView(DetailView):
    queryset = Source.objects.all()
    template_name = 'sourсe_details.html'


class ContactUsCreateViev(CreateView):
    model = ContactUs
    success_url = reverse_lazy('index')
    template_name = 'create_contactus.html'
    fields = ('email_to', 'subject', 'body')

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        body = form.cleaned_data['body']
        email_to = form.cleaned_data['email_to']

        full_email_body = f'''
        Email To: {email_to}
        Body: {body}
        '''

        contact_us.apply_async(args=(subject,), kwargs={'body': full_email_body})
        return super().form_valid(form)


class LatestRatesView(TemplateView):
    template_name = 'latest_rates_list.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['rate_list'] = get_latest_rates()
        return context

my_app/currency/templates/includes/footer.html
<!-- Footer -->
<footer class="footer sticky-bottom text-light font-small bg-dark mt-auto">

    <!-- Footer Elements -->
    <div class="container">
        <!-- Grid row-->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-12 py-2">
                <div class="mb-2 flex-center">
                    <i class="fas fa-envelope"></i>
                    <a href="{% url 'currency:contactus-create'%}" style="color: rgb(123, 196, 255); font-size: 14pt;">
                        Contact us
                    </a>
                </div>
            </div>
        </div>
        <!-- Grid row-->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-12 py-2">
                <div class="mb-2 flex-center">
                    <i class="fas fa-envelope"></i>
                    <a href="{% url 'currency:rates-last' %}" style="color: rgb(123, 196, 255); font-size: 14pt;">
                        Last rates
                    </a>
                </div>
            </div>
        </div>
        <!-- Grid row-->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-12 py-2">
                <div class="mb-2 flex-center">
                    <i class="fas fa-envelope"></i>
                    <a href="{% url 'currency:source-list' %}" style="color: rgb(123, 196, 255); font-size: 14pt;">
                        Sourse
                    </a>
                </div>
            </div>
        </div>
        <!-- Grid row-->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-12 py-3">
                <div class="mb-5 flex-center">
                    <p>{% lorem %}</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer Elements -->


    <div class="footer-copyright text-center py-3">© 2021 Copyright:
        <a href="https://mdbootstrap.com/" style="color: rgb(123, 196, 255); "> MDBootstrap.com</a>
    </div>

</footer>

my_app/currency/templates/includes/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}

my_app/currency/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:rate-list' %}">Rate List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:contactus-create' %}">Contact US</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:rates-last' %}">Latest Rates</a>
            </li>

        </ul>
        <span class="navbar-text">
            {% if request.user.is_authenticated %}
            {{ request.user.first_name }}
            <a class="btn btn-link" href="{% url 'accounts:my-profile' %}">My Profile</a>
            <a class="btn btn-link" href="{% url 'logout' %}">Log Out</a>
            {% else %}
            <a class="btn btn-warning" href="{% url 'accounts:sign-up' %}">SignUp</a>
            <a class="btn btn-link" href="{% url 'login' %}">Login</a>
            {% endif %}
        </span>
    </div>
</nav>

my_app/currency/templates/includes/paginator.html
<ul class="pagination">

    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ pagination_params }}"
            tabindex="-1">Previous</a>
    </li>
    {% endif %}

    {% for page_index in page_obj.paginator.page_range %}
    <li class="page-item {% if page_obj.number ==  page_index %} active {% endif %}">
        <a class="page-link" href="?page={{ page_index }}&{{ pagination_params }}">
            {{ page_index }}
        </a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ pagination_params }}">Next</a>
    </li>
    {% endif %}

</ul>